### ISSUE TITLE
GigaGalPrototype (and others) building fails due to hamcrest version conflict

### ISSUE THREAD

**Issue by LetterRip** [udacity/ud406#7] opened 2016-02-19 18:31 UTC
When trying to compile the later lessons the build fails with "Error:Execution failed for task ':android:dexDebug'.

com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_45\bin\java.exe'' finished with non-zero exit value 2"

"UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lorg/hamcrest/Description;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)"

**Comment by JeremySilverTongue** [comment] 2016-03-09 20:53
Hey LetterRip, thanks for the heads up. Issue was caused by the simple-json dependency. Got a fix. Will push changes today.

**Comment by JeremySilverTongue** [comment] 2016-03-09 21:31
Fixed in https://github.com/udacity/ud406/commit/d454d0976fe051c98c2ebf1cf3b74c12a5ee782a

**Closed by JeremySilverTongue** 2016-03-09 21:31 UTC
